defaults:
  - dataset: fer2013 #
  - model: resnet #
  - train: train #
  - _self_

debug:
  enabled: false
  log_shapes: false
  log_values: false
  model_summary: false

project:
  name: "joon_wandb_llm_test"
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}
dirs:
  outputs: outputs/${project.timestamp}
  subdirs: ["checkpoints", "logs", "metrics", "reports"]
logger:
  wandb:
    project_name: ${project.name}
    entity: "ailab_upstage_fastcampus"
    tags: ["tag1"]

logging:
  project_name: "multimodal-emotion"


model_manager:
  base_path: "models"
  models:
    emotion_llama:
      model_id: "ZebangCheng/Emotion-LLaMA"
      model_type: "causal_lm"
      config:
        torch_dtype: "float16"
        device_map: "auto"
    llava_next:
      model_id: "llava-hf/LLaVA-NeXT-Video-7B-32K-hf"
      model_type: "processor"
      config:
        torch_dtype: "float16"
        device_map: "auto"
    wav2vec:
      model_id: "facebook/wav2vec2-base"
      model_type: "processor"
      config:
        torch_dtype: "float16"

hydra:
  run:
    dir: ${dirs.outputs}/logs/hydra/${project.timestamp}
  output_subdir: null
  job:
    chdir: false

